### ISSUE TITLE
Multiple bugs with 3.1

### ISSUE THREAD

**Issue by Yumash** [RCRM/redmine_products#1]
Так как менеджерский состав RedmineCRM не желает вникать в проблемы, связанные с бесплатными версиями их плагинов, я оставлю реквест здесь - в надежде на то, что у разработчиков совесть крепче, чем у менеджера, отправившей меня в пешее путешествие в код продукта и ясно давшей понять что явные кейсы ошибок неинтересны компании, которая продаёт эти продукты.

```
Environment:
  Redmine version                3.1.0.devel 
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.5
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  custom_menu                    1.5.0
  inline_edit_issues             0.0.1
  quick_edit                     0.0.9
  quick_view                     0.1.0
  redmine_agile                  1.3.11
  redmine_auto_percent           0.0.1
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.2
  redmine_contacts               4.0.2
  redmine_helpdesk               0.0.15
  redmine_idonethis              0.1
  redmine_issue_history          1.0.0
  redmine_issue_status_change    1.0
  redmine_issues_tree            0.0.1
  redmine_lightbox2              0.2.2
  redmine_my_page                0.1.6
  redmine_products               2.0.0
  redmine_theme_changer          0.2.0
  redmine_workflow_enhancements  0.4.0
  redrisk                        1.0.1
  unread_issues                  1.5.0
  usability                      1.3.0
```

Список плагинов, подгружающихся при рендере:
Plugins list, loading with render

```
  Rendered plugins/redmine_products/app/views/orders/_lines.html.erb (52.2ms)
  Rendered plugins/redmine_contacts/app/views/contacts/_contact_card.html.erb (3.5ms)
  Rendered plugins/redmine_products/app/views/orders/_recent_orders.html.erb (3.7ms)
  Rendered plugins/redmine_products/app/views/orders/show.html.erb within layouts/base (135.5ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (0.8ms)
  Rendered plugins/advanced_roadmap_v2/app/views/hooks/_stylesheet.html.erb (0.1ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_html_head.html.erb (0.7ms)
  Rendered plugins/quick_edit/app/views/hooks/_quick_edit_base_head.html.erb (0.9ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_head.html.erb (0.0ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_add_css.html.erb (0.1ms)
  Rendered plugins/usability/app/views/hooks/usability/_html_head.html.erb (3.5ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.4ms)
  Rendered plugins/quick_edit/app/views/hooks/_quick_edit_base_bottom.html.erb (0.5ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_tooltip.html.erb (1.1ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom.html.erb (0.3ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_worktime_ext.html.erb (0.8ms)
  Rendered plugins/usability/app/views/hooks/usability/_body_bottom.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (3.9ms)
```

1. Продукт не привязывается к категории.
1. Cannot tie a product to category

```
Started POST "/projects/presale/products" for 5.228.36.122 at 2015-09-10 12:14:01 +0300
Processing by ProductsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"token", "product"=>{"name"=>"Test Name", "code"=>"Test Code", "status_id"=>"1", "category_id"=>"6", "price"=>"42", "currency"=>"RUB", "description"=>"Test description", "tag_list"=>"test tag"}, "commit"=>"Сохранить", "project_id"=>"presale"}
  Current user: me
(HERE IS ERROR )WARNING: Can't mass-assign protected attributes for Product: category_id, description
        lib/redmine/safe_attributes.rb:84:in `safe_attributes='
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'**
Redirected to http://redmine.corp.yumalabs.ru/products/6
Completed 302 Found in 32ms (ActiveRecord: 4.8ms)
Started GET "/products/6" for 5.228.36.122 at 2015-09-10 12:14:01 +0300
Processing by ProductsController#show as HTML
  Parameters: 
  Current user: 
  Rendered plugins/redmine_products/app/views/products/show.html.erb within layouts/base (20.5ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.1ms)
  Rendered plugins/advanced_roadmap_v2/app/views/hooks/_stylesheet.html.erb (0.1ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_html_head.html.erb (0.7ms)
  Rendered plugins/quick_edit/app/views/hooks/_quick_edit_base_head.html.erb (1.5ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_head.html.erb (0.0ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_add_css.html.erb (0.2ms)
  Rendered plugins/usability/app/views/hooks/usability/_html_head.html.erb (5.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.5ms)
  Rendered plugins/quick_edit/app/views/hooks/_quick_edit_base_bottom.html.erb (0.9ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_tooltip.html.erb (0.9ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom.html.erb (0.4ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_worktime_ext.html.erb (1.1ms)
  Rendered plugins/usability/app/views/hooks/usability/_body_bottom.html.erb (0.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (4.3ms)
Completed 200 OK in 148ms (Views: 117.8ms | ActiveRecord: 18.1ms
```

2. Никакое добавление полей не срабатывает.
2. Cannot save fields in order

Если я добавляю к новому заказу произвольные строки - они просто нигде не сохраняются (и соответственно, не выводятся)
If i am adding non-product-tied strings to a new order - there's no chance to see them anywhere - there's no place to save them according to DB struct.

Если я добавляю к новому заказу продукт из селектбокса - в добавлении не показывается его название (как на картинках с сайта) - просто описание и автозаполнение количества, цены.
If i am adding existing product to order, product name not shows - only comment field and qnt/price autocompleted fields.

В итоге при сохранении заказа сохраняется только сумма - все поля сбрасываются.
In result, only sum is saved while saving order.

![2015-09-10 12 24 29](https://cloud.githubusercontent.com/assets/6568685/9784935/23bd4cc8-57b7-11e5-9b15-f5d8a6deb64e.png)
![2015-09-10 12 24 34](https://cloud.githubusercontent.com/assets/6568685/9784932/23934bd0-57b7-11e5-82be-d7f541afbfd9.png)
![2015-09-10 12 25 00](https://cloud.githubusercontent.com/assets/6568685/9784933/239601ea-57b7-11e5-87a2-e790cb8c0d9d.png)
![2015-09-10 12 25 10](https://cloud.githubusercontent.com/assets/6568685/9784930/23908aee-57b7-11e5-801b-6c6100d0542c.png)
![2015-09-10 12 25 22](https://cloud.githubusercontent.com/assets/6568685/9784931/2392a7e8-57b7-11e5-8190-fb35ac143dde.png)
![2015-09-10 12 26 00](https://cloud.githubusercontent.com/assets/6568685/9784934/23965852-57b7-11e5-8018-1c6a8a809dd5.png)

**Comment by Yumash** [comment]
Последняя картинка показывает что после любого редактирования сбрасывается сумма заказа.
The last picture shows that after any edit the sum clears
